import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";
import Link from "next/link"
import { Beaker } from "lucide-react"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Health Mapping Hub",
  description: "Generated by create next app",
};

const montserrat = Montserrat();

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (

    <html lang="en">
      <body
        className={`${montserrat.className} antialiased bg-white bg-[radial-gradient(60%_120%_at_50%_50%,hsla(0,0%,100%,0)_0,rgba(137,196,244,0.5)_100%)]`}
      >
        <header className="sticky top-0 z-3 w-full border-b bg-background/95 flex justify-evenly backdrop-blur supports-[backdrop-filter]:bg-background/90 px-4">
          <div className="container flex h-16 items-center">
            <Link href="/" className="flex items-center gap-2 font-semibold">
              <Beaker className="h-8 w-8 text-blue-600" />
              <span className="text-lg">Health Mapping Hub</span>
            </Link>
            <nav className="ml-auto flex gap-4 sm:gap-12">
              <Link href="/" className="text-lg font-medium hover:underline underline-offset-8">Find Trials</Link>
              <Link href="/contact" className="text-lg font-medium hover:underline underline-offset-8">Contact</Link>
              <button>
                <Avatar>
                  <AvatarImage src="globe.svg" alt="avatar" />
                  <AvatarFallback>
                    <AvatarImage src="" alt="avatar fallback"></AvatarImage>
                  </AvatarFallback>
                </Avatar>
              </button>
            </nav>
          </div>
        </header>

        
        {children}
        <footer className="m-0 z-3 flex justify-center items-center w-full py-4 bg-white">
          <div className="container flex flex-col items-center justify-between gap-4 md:flex-row">
            <div className="flex items-center gap-2">
              <span className="font-semibold">Health Mapping Hub</span>
            </div>
            <p className="text-center text-sm text-muted-foreground md:text-left">
              &copy; Health Mapping Hub, 2025. All rights reserved.
            </p>
            <nav className="flex gap-4 sm:gap-6">
              <Link href="/terms" className="text-md font-medium hover:underline underline-offset-8 transition-colors">Terms</Link>
              <Link href="/privacy" className="text-md font-medium hover:underline underline-offset-8 transition-colors">Privacy</Link>
              <Link href="/contact" className="text-md font-medium hover:underline underline-offset-8 transition-colors">Contact</Link>
            </nav>
          </div>
        </footer>
      </body>
    </html>
    
  );
}

